/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { ExternalUser } from '../models';
// @ts-ignore
import { RegisterUser200Response } from '../models';
// @ts-ignore
import { TrackActivity200Response } from '../models';
// @ts-ignore
import { TrackActivityInput } from '../models';
/**
 * ExternalApi - axios parameter creator
 * @export
 */
export const ExternalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} apiKey 
         * @param {ExternalUser} externalUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (apiKey: string, externalUser: ExternalUser, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKey' is not null or undefined
            assertParamExists('registerUser', 'apiKey', apiKey)
            // verify required parameter 'externalUser' is not null or undefined
            assertParamExists('registerUser', 'externalUser', externalUser)
            const localVarPath = `/external/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apiKey != null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(externalUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} apiKey 
         * @param {TrackActivityInput} trackActivityInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackActivity: async (apiKey: string, trackActivityInput: TrackActivityInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKey' is not null or undefined
            assertParamExists('trackActivity', 'apiKey', apiKey)
            // verify required parameter 'trackActivityInput' is not null or undefined
            assertParamExists('trackActivity', 'trackActivityInput', trackActivityInput)
            const localVarPath = `/external/activities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apiKey != null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trackActivityInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExternalApi - functional programming interface
 * @export
 */
export const ExternalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExternalApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} apiKey 
         * @param {ExternalUser} externalUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(apiKey: string, externalUser: ExternalUser, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(apiKey, externalUser, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} apiKey 
         * @param {TrackActivityInput} trackActivityInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackActivity(apiKey: string, trackActivityInput: TrackActivityInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TrackActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.trackActivity(apiKey, trackActivityInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ExternalApi - factory interface
 * @export
 */
export const ExternalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExternalApiFp(configuration)
    return {
        /**
         * 
         * @param {string} apiKey 
         * @param {ExternalUser} externalUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(apiKey: string, externalUser: ExternalUser, options?: any): AxiosPromise<RegisterUser200Response> {
            return localVarFp.registerUser(apiKey, externalUser, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} apiKey 
         * @param {TrackActivityInput} trackActivityInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackActivity(apiKey: string, trackActivityInput: TrackActivityInput, options?: any): AxiosPromise<TrackActivity200Response> {
            return localVarFp.trackActivity(apiKey, trackActivityInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExternalApi - object-oriented interface
 * @export
 * @class ExternalApi
 * @extends {BaseAPI}
 */
export class ExternalApi extends BaseAPI {
    /**
     * 
     * @param {string} apiKey 
     * @param {ExternalUser} externalUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalApi
     */
    public registerUser(apiKey: string, externalUser: ExternalUser, options?: AxiosRequestConfig) {
        return ExternalApiFp(this.configuration).registerUser(apiKey, externalUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} apiKey 
     * @param {TrackActivityInput} trackActivityInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalApi
     */
    public trackActivity(apiKey: string, trackActivityInput: TrackActivityInput, options?: AxiosRequestConfig) {
        return ExternalApiFp(this.configuration).trackActivity(apiKey, trackActivityInput, options).then((request) => request(this.axios, this.basePath));
    }
}
