/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ActivityType = {
    UserSignUp: 'USER_SIGN_UP',
    Referral: 'REFERRAL',
    GameClick: 'GAME_CLICK',
    SocialClick: 'SOCIAL_CLICK',
    ExternalMilestone: 'EXTERNAL_MILESTONE',
    ExternalCumulative: 'EXTERNAL_CUMULATIVE',
    ActivityResumed: 'ACTIVITY_RESUMED',
    ActivityPaused: 'ACTIVITY_PAUSED',
    ActivityStopped: 'ACTIVITY_STOPPED',
    ForegroundServiceStart: 'FOREGROUND_SERVICE_START',
    ForegroundServiceStop: 'FOREGROUND_SERVICE_STOP',
    GameInstalled: 'GAME_INSTALLED'
} as const;

export type ActivityType = typeof ActivityType[keyof typeof ActivityType];



