/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @enum {string}
 */

export const ActivityType = {
    UserSignUp: 'USER_SIGN_UP',
    Referral: 'REFERRAL',
    GameClick: 'GAME_CLICK',
    ExternalMilestone: 'EXTERNAL_MILESTONE',
    ExternalCumulative: 'EXTERNAL_CUMULATIVE',
    ActivityResumed: 'ACTIVITY_RESUMED',
    ActivityPaused: 'ACTIVITY_PAUSED',
    ActivityStopped: 'ACTIVITY_STOPPED',
    ForegroundServiceStart: 'FOREGROUND_SERVICE_START',
    ForegroundServiceStop: 'FOREGROUND_SERVICE_STOP',
    GameInstalled: 'GAME_INSTALLED',
    SocialClick: 'SOCIAL_CLICK',
    SocialAuth: 'SOCIAL_AUTH',
    SocialOpenlink: 'SOCIAL_OPENLINK',
    SocialLike: 'SOCIAL_LIKE',
    SocialFollow: 'SOCIAL_FOLLOW',
    SocialShare: 'SOCIAL_SHARE',
    EmailSocialAuth: 'EMAIL_SOCIAL_AUTH',
    XSocialAuth: 'X_SOCIAL_AUTH',
    DiscordSocialAuth: 'DISCORD_SOCIAL_AUTH',
    EmailSocialClick: 'EMAIL_SOCIAL_CLICK',
    XSocialClick: 'X_SOCIAL_CLICK',
    XSocialHashtag: 'X_SOCIAL_HASHTAG',
    DiscordSocialClick: 'DISCORD_SOCIAL_CLICK',
    XSocialOpenlink: 'X_SOCIAL_OPENLINK',
    DiscordSocialOpenlink: 'DISCORD_SOCIAL_OPENLINK',
    XSocialLike: 'X_SOCIAL_LIKE',
    DiscordSocialLike: 'DISCORD_SOCIAL_LIKE',
    XSocialFollow: 'X_SOCIAL_FOLLOW',
    DiscordSocialFollow: 'DISCORD_SOCIAL_FOLLOW',
    XSocialShare: 'X_SOCIAL_SHARE',
    DiscordSocialShare: 'DISCORD_SOCIAL_SHARE'
} as const;

export type ActivityType = typeof ActivityType[keyof typeof ActivityType];



