/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model Banner
 * @export
 * @interface Banner
 */
export interface Banner {
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'subtitle': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'endTime': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'startTime': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'gameId': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'alt': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Banner
     */
    'id': string;
}

