/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GoalCreateInput } from './goal-create-input';
// May contain unused imports in some cases
// @ts-ignore
import { GoalUpdateInputAllOf } from './goal-update-input-all-of';

/**
 * @type GoalUpdateInput
 * @export
 */
export type GoalUpdateInput = GoalCreateInput & GoalUpdateInputAllOf;


