/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActivityType } from './activity-type';

/**
 * Model Goal
 * @export
 * @interface Goal
 */
export interface Goal {
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'questId': string;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'objectId': string | null;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'bannerUrl': string | null;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'instructions': string | null;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'description': string | null;
    /**
     * 
     * @type {ActivityType}
     * @memberof Goal
     */
    'activity': ActivityType;
    /**
     * 
     * @type {number}
     * @memberof Goal
     */
    'target': number;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    'id': string;
}



