/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuestScheduleUpdateInputAllOf
 */
export interface QuestScheduleUpdateInputAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof QuestScheduleUpdateInputAllOf
     */
    'recurring': boolean;
    /**
     * 
     * @type {string}
     * @memberof QuestScheduleUpdateInputAllOf
     */
    'questScheduleId': string;
}

