/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model QuestSchedule
 * @export
 * @interface QuestSchedule
 */
export interface QuestSchedule {
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'questId': string;
    /**
     * 
     * @type {boolean}
     * @memberof QuestSchedule
     */
    'processed': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QuestSchedule
     */
    'recurring': boolean;
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'endTime': string | null;
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'startTime': string;
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof QuestSchedule
     */
    'id': string;
}

