/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TrackActivity200ResponseData
 */
export interface TrackActivity200ResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof TrackActivity200ResponseData
     */
    'processed': boolean;
    /**
     * 
     * @type {string}
     * @memberof TrackActivity200ResponseData
     */
    'occurence': string;
    /**
     * 
     * @type {number}
     * @memberof TrackActivity200ResponseData
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof TrackActivity200ResponseData
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof TrackActivity200ResponseData
     */
    'activityId': string;
}

