/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TrackBatchActivitiesByUser200Response
 */
export interface TrackBatchActivitiesByUser200Response {
    /**
     * 
     * @type {number}
     * @memberof TrackBatchActivitiesByUser200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof TrackBatchActivitiesByUser200Response
     */
    'message': string;
}

