/* tslint:disable */
/* eslint-disable */
/**
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Gender } from './gender';

/**
 * Model User
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastLogin': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'verified': boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'mergedWith': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'gameId': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'externalId': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'referredById': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'enableNotifications': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'hasAcceptedLegal': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'hasOnboarded': boolean;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    'gender': Gender;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'birthYear': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar': string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'remainingReferrals': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'code': string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'usertag': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phoneNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'authId': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'originalCreationDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id': string;
}



